version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
